### ISSUE TITLE
Maven Compiling Issue (on NetBeans IDE)

### ISSUE THREAD

**Issue by LewisTehMinerz** [Comprehensive-Minecraft-Archive-Network/CMAN-Java#2]
THIS IS A GLOBAL ISSUE.

When building using NetBeans IDE (using the maven-compiler-plugin) it generates a .JAR which can only be ran through java -jar and not double clicking. Not sure if this is just NetBeans IDE or it's on Eclipse too.

**Comment by randomtestfive** [comment]
Just tested with Eclipse, double clicking works.

**Comment by LewisTehMinerz** [comment]
I don't think NetBeans inserted a Main-Class in the manifest, I think that's why.

**Comment by LewisTehMinerz** [comment]
Closing issue: 2 months old.

**Comment by LewisTehMinerz** [comment]
Note: This issue was written BEFORE the issue template was made. Do not write any issues without using the template or they will be denied without consideration. Only make issues USING THE TEMPLATE.
