### ISSUE TITLE
Exception: NoSuchElementException

### ISSUE THREAD

**Issue by LewisTehMinerz** [Comprehensive-Minecraft-Archive-Network/CMAN-Java#3]
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:907)
	at java.util.Scanner.next(Scanner.java:1416)
	at cman.CMAN.check_for_updates(CMAN.java:65)
	at cman.CMAN.main(CMAN.java:224)

**Comment by randomtestfive** [comment]
Is this nightly or stable, because I think check_for_updates won't work on stable because it uses the wrong url for the version.

**Comment by LewisTehMinerz** [comment]
Nightly.

**Comment by randomtestfive** [comment]
Is this still happening? I can't trigger this.

**Comment by LewisTehMinerz** [comment]
I can by just running it. Review the following paste: http://pastebin.com/zAbrPQp1

**Comment by randomtestfive** [comment]
There's nothing on line 65 though...

**Comment by LewisTehMinerz** [comment]
There must be, why else would it say there's something on line 65?

Line 65 [for me at least] = String latestversion = s.next();

**Comment by randomtestfive** [comment]
Are you sure you have the latest version from the repository?

**Comment by LewisTehMinerz** [comment]
Yes. I redownloaded quite recently.

**Comment by randomtestfive** [comment]
I have no idea then, your line 65 is supposed to be line 80, so I have no idea what is actually happening.

**Comment by LewisTehMinerz** [comment]
Redownloading and re-running...

Results: 

Different exception. NPE from trying to set the icon. Closing issue and creating a new one.

**Comment by LewisTehMinerz** [comment]
Note: This issue was written BEFORE the issue template was made. Do not write any issues without using the template or they will be denied without consideration. Only make issues USING THE TEMPLATE.
