### ISSUE TITLE
Maven defaulting to Java 1.5

### ISSUE THREAD

**Issue by randomtestfive** [Comprehensive-Minecraft-Archive-Network/CMAN-Java#9]
[//]: # "Thanks for reporting an issue for CMAN-Java! Do not delete this line as it is not included in the issue report. The following template MUST BE FOLLOWED, else, your issue will be closed. There are exceptions to this rule like feature requests, however. Thank you, CMAN Team"

Build Of CMAN
=============
[//]: # "Write your build here."
Instances build

Description Of Issue
====================
For maven compiling, a version must be provided or it will default to 1.5 instead of 1.7 or 1.8
[//]: # "Describe your issue here."

Reproduction Steps
==================
Attempt to build using maven
[//]: # "Write your reproduction steps here."

**Comment by randomtestfive** [comment]
Setting it to use 1.7 instead of 1.8 lets the build pass, but there isn't really a point to test in 1.8 then.

**Comment by randomtestfive** [comment]
Running in 1.8 fails the 1.7 build, like [here](https://travis-ci.org/Comprehensive-Minecraft-Archive-Network/CMAN-Java/builds/114934539).

**Comment by LewisTehMinerz** [comment]
Well, kill the 1.8 build then.

**Comment by randomtestfive** [comment]
The version has been changed to compile using 1.8 now.
